# Here we will work with Rows 
import pandas as pd
df_orders = pd.read_csv('files/orders.csv')
print(df_orders.head(5))

print(df_orders.index) #By default my rangeIndex starts at 0 and ends at howsoever rows we have with a default step of 1. 

# Sometimes it may happen that the value at index we may want to change the index values with one of the columns (e.g., primary key)
# meaning index should be uniqueidentifier for that row.
# we want our index to be unique at every row.
#In df_orders looks like OrderId can be used as an Index because each of the values are unique in OrderId. 

df_orders.set_index('OrderID', inplace=True) #This will set the 'OrderID' column as the index of the DataFrame and modify the original DataFrame in place. The set_index() method is used to set a specific column as the index of the DataFrame. The inplace parameter is used to specify whether we want to modify the original DataFrame or return a new DataFrame with the new index. If inplace=True, it will modify the original DataFrame and return None. If inplace=False (which is the default), it will return a new DataFrame with the new index and leave the original DataFrame unchanged. This is an example of how to use the set_index() method to change the index of a DataFrame by setting a specific column as the new index and modifying the original DataFrame in place by setting inplace=True.
print(df_orders.head(5)) #This will print the first 5 rows of the DataFrame with the 'OrderID' column as the index. The index is shown on the left side and the columns are shown on the top. The values of the DataFrame are shown in the cells where the index and columns intersect. This is an example of how to change the index of a DataFrame by setting a specific column as the new index and modifying the original DataFrame in place using the set_index() method with inplace=True.    

# Now our columns reduced by 1. We have 'OrderID' as index and rest of the columns are 'CustomerID', 'OrderDate', 'OrderStatus', and 'OrderAmount'.
#If we want to reset the index back to default numeric index starting from 0, we can use the reset_index() method as below:
df_orders.reset_index(inplace=True) #This will reset the index of the DataFrame back to the default numeric index starting from 0 and modify the original DataFrame in place. The reset_index() method is used to reset the index of the DataFrame back to the default numeric index. The inplace parameter is used to specify whether we want to modify the original DataFrame or return a new DataFrame with the reset index. If inplace=True, it will modify the original DataFrame and return None. If inplace=False (which is the default), it will return a new DataFrame with the reset index and leave the original DataFrame unchanged. This is an example of how to use the reset_index() method to reset the index of a DataFrame back to the default numeric index and modify the original DataFrame in place by setting inplace=True.
print(df_orders.head(5)) #This will print the first 5 rows of the DataFrame with the default numeric index starting from 0. The index is shown on the left side and the columns are shown on the top. The values of the DataFrame are shown in the cells where the index and columns intersect. This is an example of how to reset the index of a DataFrame back to the default numeric index using the reset_index() method with inplace=True to modify the original DataFrame in place.

# Grabbing rows via index
#Grabbing based on its numeric index location
print(df_orders.iloc[0]) #This will print the first row of the DataFrame which is a Series object. The index of the Series will be the same as the columns of the DataFrame and the values of the Series will be the values of the first row in the DataFrame. This is an example of how to access a specific row in a DataFrame using its numeric index location with the iloc[] method. The iloc[] method is used to access rows and columns in a DataFrame by their integer position, while the loc[] method is used to access rows and columns by their label index location. In this case, since we are using iloc[0], it will return the first row of the DataFrame as a Series object.


#Grabbing based on its label index location

df_orders.set_index('OrderID', inplace=True)

print(df_orders.loc[1001]) #this throws error because the index of the DataFrame is now 'OrderID' and the value '1001' is not present in the index. The loc[] method is used to access rows and columns in a DataFrame by their label index location, so we need to provide a valid label that exists in the index to access the corresponding row. If we want to access a specific row using its label index location, we can do it via below:

# print(df_orders.OrderID) #This throws an error because 'OrderID' is now the index of the DataFrame and we cannot access it as a column. The columns of the DataFrame are 'CustomerID', 'OrderDate', 'OrderStatus', and 'OrderAmount'. Since 'OrderID' is now the index, we can access it using the index of the DataFrame instead of as a column. For example, if we want to access the row with 'OrderID' 1001, we can do it via below:
print(df_orders.loc[1001]) #This will print the row with 'OrderID'

# For grabbing multiple rows. 
print(df_orders.iloc[0:4])

# Grabbing multiple rows based on label index location
print(df_orders.loc[1001:1004]) #This will print the rows with 'OrderID' from 1001 to 1004 inclusive. The loc[] method is used to access rows and columns in a DataFrame by their label index location, so we can specify a range of labels to access multiple rows. In this case, since we are using loc[1001:1004], it will return the rows with 'OrderID' from 1001 to 1004 inclusive as a DataFrame object.

# Or write it like below as well:
print(df_orders.loc[[1001, 1002, 1003, 1004]]) #This will also print the rows with 'OrderID' 1001, 1002, 1003, and 1004. The loc[] method can also be used to access specific rows by providing a list of labels. In this case, since we are using loc[[1001, 1002, 1003, 1004]], it will return the rows with 'OrderID' 1001, 1002, 1003, and 1004 as a DataFrame object. This is another way of accessing multiple rows in a DataFrame using the loc[] method by providing a list of labels instead of a range of labels.

#Remove rows
df_orders.drop(1001, axis=0, inplace=True) #This will drop the row with 'OrderID' 1001 from the DataFrame and modify the original DataFrame in place. The drop() method is used to remove rows or columns from a DataFrame. The first parameter is the label of the row or column to be dropped, and the axis parameter is used to specify whether we want to drop a row (axis=0) or a column (axis=1). The inplace parameter is used to specify whether we want to modify the original DataFrame or return a new DataFrame with the row dropped. If inplace=True, it will modify the original DataFrame and return None. If inplace=False (which is the default), it will return a new DataFrame with the row dropped and leave the original DataFrame unchanged. This is an example of how to use the drop() method to remove a specific row from a DataFrame by providing the label of the row and setting axis=0 to indicate that we want to drop a row, and setting inplace=True to modify the original DataFrame in place.
print(df_orders.head(5)) #This will print the first 5 rows of the DataFrame after dropping the row with 'OrderID' 1001. The index is shown on the left side and the columns are shown on the top. The values of the DataFrame are shown in the cells where the index and columns intersect. This is an example of how to verify that a specific row has been removed from a DataFrame by printing the first few rows of the DataFrame after using the drop() method to remove the row.  

#Sometimes selecting only the rows that we want vs dropping the rows that we don't want can be more efficient. For example, if we want to select only the rows with 'OrderID' 1002 and 1003, we can do it via below:
print(df_orders.loc[[1002, 1003]]) #This will print the rows with 'OrderID' 1002 and 1003. The loc[] method is used to access rows and columns in a DataFrame by their label index location, so we can specify a list of labels to access specific rows. In this case, since we are using loc[[1002, 1003]], it will return the rows with 'OrderID' 1002 and 1003 as a DataFrame object. This is an example of how to select specific rows from a DataFrame using the loc[] method by providing a list of labels for the rows we want to select instead of dropping the rows we don't want. 

# If we were to append new row to the dataframe then we make use of df.append() method. However, this method is going to be deprecated in future so we recommend to use pd.concat() method instead to append new rows to a DataFrame. For example, if we want to append a new row with 'OrderID' 1005, 'CustomerID' 2005, 'OrderDate' '2021-01-05', 'OrderStatus' 'Shipped', and 'OrderAmount' 500, we can do it via below:
new_row = pd.DataFrame({'OrderID': [1005], 'CustomerID': [2005], 'OrderDate': ['2021-01-05'], 'OrderStatus': ['Shipped'], 'OrderAmount': [500]}) #This will create a new DataFrame with a single row containing the values for the new row we want to append to the original DataFrame. The columns of the new DataFrame should match the columns of the original DataFrame for the append operation to work correctly.
df_orders = pd.concat([df_orders, new_row], ignore_index=True) #This will append the new row to the original DataFrame and return a new DataFrame with the new row included. The concat() method is used to concatenate two or more DataFrames along a particular axis. In this case, we are concatenating the original DataFrame and the new DataFrame along the rows (axis=0) to append the new row to the original DataFrame. The ignore_index parameter is used to specify whether we want to ignore the index of the original DataFrame and create a new index for the resulting DataFrame. If ignore_index=True, it will create a new index for the resulting DataFrame starting from 0. If ignore_index=False (which is the default), it will keep the index of the original DataFrame and append the new row with its own index. This is an example of how to use the pd.concat() method to append a new row to a DataFrame by concatenating the original DataFrame with a new DataFrame containing the values for the new row, and using ignore_index=True to create a new index for the resulting DataFrame.
print(df_orders.tail(5)) #This will print the last 5 rows of the DataFrame after appending the new row. The index is shown on the left side and the columns are shown on the top. The values of the DataFrame are shown in the cells where the index and columns intersect. This is an example of how to verify that a new row has been appended to a DataFrame by printing the last few rows of the DataFrame after using the pd.concat() method to append the new row.

#Imp .................................................
# Note that Pandas does not complain if we have duplicate index values in the DataFrame. However, it is generally recommended to have unique index values in a DataFrame to avoid any potential issues with data manipulation and analysis. If we have duplicate index values, it can lead to unexpected results when performing operations on the DataFrame, such as selecting specific rows or performing groupby operations. Therefore, it is important to ensure that the index of a DataFrame has unique values to maintain the integrity of the data and avoid any potential issues with data manipulation and analysis.