import pandas as pd
# Part 2 of series lesson

# Let's create 2 series object via dictionary of Imaginary Sales Data for 1st and 2nd quarter for Global Company 
sales_Q1 = pd.Series({'Jan':1000,'Feb':1500,'Mar':2000}) #This will create a Series object with the index as 'Jan','Feb','Mar' and the values as 1000,1500,2000. The index is shown on the left side and the values are shown on the right side.
print(sales_Q1) #This will print the Series object which is a one-dimensional array with the index as 'Jan','Feb','Mar' and the values as 1000,1500,2000. The index is shown on the left side and the values are shown on the right side.       

sales_Q2 = pd.Series({'Apr':1200,'May':1700,'Jun':2200}) #This will create a Series object with the index as 'Apr','May','Jun' and the values as 1200,1700,2200. The index is shown on the left side and the values are shown on the right side.
print(sales_Q2) #This will print the Series object which is a one-dimensional array with the index as 'Apr','May','Jun' and the values as 1200,1700,2200. The index is shown on the left side and the values are shown on the right side.       

sales_Q1.keys() #This will return the index of the Series object which is 'Jan','Feb','Mar'
print(sales_Q1.keys()) #This will print the index of the Series object which is 'Jan','Feb','Mar'   

# Basic operations between 2 series
# Since these are built on top of numpy arrays, we can perform broadcast operations between the two series. 
print(sales_Q1 * 10) #This will multiply each element in the Series by 10 and return a new Series with the result. The index of the new Series will be the same as the original Series and the values will be the result of the multiplication. This is an example of broadcasting in Pandas, where we can perform operations on a Series with a scalar value and it will apply that operation to each element in the Series.           
print(sales_Q1 / 100) #This will divide each element in the Series by 100 and return a new Series with the result. The index of the new Series will be the same as the original Series and the values will be the result of the division. This is another example of broadcasting in Pandas.

# If we were to do a sum on sales_Q1 and sales_Q2 then Pandas will sum both 
# the values and the index of the resulting Series will be the union of the index of both Series. The values for the indices that are present in both Series will be the sum of the values from both Series, while the values for the indices that are present in only one of the Series will be the same as the original value from that Series. This is an example of how Pandas handles operations between Series with different indices.
print(sales_Q1 + sales_Q2) #This will add the two Series together and return a new Series with the result. The index of the new Series will be the union of the index of both Series and the values will be the sum of the values from both Series for the indices that are present in both Series, and the same as the original value from that Series for the indices that are present in only one of the Series. This is an example of how Pandas handles operations between Series with different indices.

# The above command returns NaN for the indices that are not present in both Series because when we perform an operation between two Series with different indices, Pandas will align the Series based on their indices and perform the operation on the aligned values. If an index is not present in one of the Series, it will be treated as if it has a value of NaN (Not a Number) for that index. Therefore, when we add sales_Q1 and sales_Q2 together, the indices 'Jan','Feb','Mar' from sales_Q1 will have NaN values in the resulting Series because they are not present in sales_Q2, and the indices 'Apr','May','Jun' from sales_Q2 will have NaN values in the resulting Series because they are not present in sales_Q1. The indices that are present in both Series, which is none in this case, will have the sum of the values from both Series.

sales_Q3 = pd.Series({'Jan':1200,'Feb':1700,'Mar':2200}) 
# Now if we were to do a sum on sales_Q1 and sales_Q3 then Pandas will sum both the values and the index of the resulting Series will be the union of the index of both Series. The values for the indices that are present in both Series will be the sum of the values from both Series, while the values for the indices that are present in only one of the Series will be the same as the original value from that Series. This is an example of how Pandas handles operations between Series with different indices.
print(sales_Q1 + sales_Q3) #This will add the two Series together and return a new Series with the result. The index of the new Series will be the union of the index of both Series and the values will be the sum of the values from both Series for the indices that are present in both Series, and the same as the original value from that Series for the indices that are present in only one of the Series. In this case, since both Series have the same indices 'Jan','Feb','Mar', the resulting Series will have those indices and the values will be the sum of the values from both Series for those indices. This is an example of how Pandas handles operations between Series with different indices.

#Instead of NaN durin Sum we can fill it with  some value using fill_value parameter in the add() method. The fill_value parameter is used to specify a value to fill in for the indices that are not present in both Series when performing an operation between two Series with different indices. For example, if we want to fill the NaN values with 0 when adding sales_Q1 and sales_Q2 together, we can do it via below:
print(sales_Q1.add(sales_Q2, fill_value=0)) #This will add the two Series together and return a new Series with the result. The index of the new Series will be the union of the index of both Series and the values will be the sum of the values from both Series for the indices that are present in both Series, and 0 for the indices that are not present in both Series. This is an example of how to use the fill_value parameter in the add() method to fill in for the indices that are not present in both Series when performing an operation between two Series with different indices.    

# Note that pandas converts series data from an Integer to Float while doing operations. This is because when we perform operations between Series with different indices, pandas will align the Series based on their indices and perform the operation on the aligned values. If an index is not present in one of the Series, it will be treated as if it has a value of NaN (Not a Number) for that index. Since NaN is a floating-point value, pandas will convert the data type of the resulting Series to float to accommodate the NaN values. Therefore, when we add sales_Q1 and sales_Q2 together, the resulting Series will have a data type of float because it contains NaN values for the indices that are not present in both Series.


